# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TripodNinja ðŸŽ¥ Krishna Bhamidipati
email: email@krishna.video
description: 'Freelance videographer and sound engineer with a love for tech and classical music.'
baseurl: ''
url: https://krishna.video
twitter_username: tripodninja
github_username: NaanProphet

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-121779698-1

# Plugin settings
reading_time:
  second_plural: "sec"
  minute_singular: "min"
  minute_plural: "min"

algolia:
  application_id: 3OKHIO3QMO
  index_name:     tripodninja
  search_only_api_key: b262a8e29b271995e7731e5381609ff3
